import React from 'react'
import Header from './Header'
import Footer from './Footer'



export default function TermsConditions(){

    return(
        <>
        <Header/>
        <div className="wrap-privacy">
        <div className='container py-5'>
        <div style={{height: "15vh"}} className="d-block mx-auto">
            <h1>Terms & Conditions</h1>
            </div>
            <p>These Terms of Use govern access and use of the mobile application – <span className='point-color' >“Btskola”(“Platform”) </span>owned and operated by Bitcipher Labs LLP. User shall mean any person/individual, who visits, uses, deals with and/ or transacts through the website / app / referrals / API or avails other Services (defined below) provided by the Platform.</p>
            <p>By accessing, using or clicking “I agree” to any of the services made available by BitFlash through BitFlash, you agree that you have read, understood and accepted all of the terms and conditions contained in this Terms of Use (the “Terms/Terms of Use”), our Privacy Policy available at https://bitflash.io/privacy-policy and AML Policy available at https:// bitflash.io/aml-policy</p>
            <p>As used herein:</p>

            <p> <span className='point-color' >"LLP", "BitFlash", "Ourselves", "Us", "Our"</span> and <span className='point-color' >"We"</span> refers to the owners, operators, employees, directors, officers, agents, insurers, suppliers, and attorneys of the Platform.
            </p>
            <p> <span className='point-color' >"Client", "Customer", "User", "You"</span> and <span className='point-color' >"Your"</span> refers to you, resident of India above the age of 18 years of age</p>
            <p>"Virtual Currency" or "VCs" refers to cryptocurrencies, i.e., digital money, which is issued and usually controlled by its developers, and used and accepted among the members of a specific virtual community, including but not limited to Bitcoins, NEO, Ether, Litecoin, Ripple, Dash, etc. The usage of terms “Virtual Currency” or “VC” herein shall include only those virtual currencies that the LLP in its sole discretion, decides to facilitate through the Platform.</p>
            <p>Save and except as required under any applicable law or force majeure event, as long as you agree to and comply with these Terms of Use, BitFlash grants to You a limited personal, non-exclusive, non-transferable, non-sub-licensable, revocable and limited right to access and use the Platform and the Service as per these Terms</p>
            <p>You represent and warrant that you (a) are at least 18 years old and competent to form a binding contract in India, (b) are an individual with full legal capacity and authority to enter into these Terms, and (c) have not previously been suspended or removed from using our Services and/or the Platform and /or any other platform owned / operated by the LLP or any other VC platform.</p>
            <h2>1. About BitFlash:</h2>
            <p><span className='point-color' >1.1</span> BitFlash is an online digital cryptocurrency exchange aggregation platform for Virtual Currencies also known as VC, tokens, digital tokens or cryptographic currency. The Platform provides access to an online digital assets exchange that currently facilitates:</p>
            <p><span className='point-color' >a</span> online trading of VCs including sale and purchase (either using fiat currency or another form of VC);</p>
            <p><span className='point-color' >b</span> transfer of funds from a User’s BitFlash Wallet into its users linked bank account and vice versa, and;</p>
            <p><span className='point-color' >c</span> online storage of VC owned by the Users (collectively the " Services ").</p>
            <p><span className='point-color' >1.2</span> BitFlash is neither the creator nor the administrator of any Virtual Currency. It merely acts as an aggregator and technology intermediary between the User and the various VC exchanges across the globe through external platforms and APIs.</p>       



 <h2>2. User Registration</h2>
 <p><span className='point-color' >2.1</span> In order to enjoy the Services on the BitFlash Platform, User is required to create an account and register itself on the Platform (“BitFlash Account”). User will be required to provide certain information as prompted by the account registration form. You represent and warrant that: (a) all required registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information. You may delete your own BitFlash Account at anytime, for any reason, by following the instructions on the Platform provided. However, the information provided by You shall be retained for compliance to applicable laws including but not limited to the Prevention of the Money -Laundering Act 2002, the Prevention of Money Laundering (Maintenance of Records) Rules 2005 and other guidelines/policies issued by the government authorities or the regulatory bodies in this regard. Please review the Privacy Policy and FAQ for more details.</p>

<p><span className="point-color">2.2</span> The information we request may include certain personal information, including, but notlimited to:</p>
<p><span className='point-color' >a</span> Personal Information like your name, address, telephone number, e-mail address, date of birth, photo</p>
<p><span className='point-color' >b</span> Government authorised identification card like PAN card, passport etc., as may be requiredby the LLP;</p>
<p><span className='point-color' >c</span> User’s bank account details, such as the name of the bank, the account type, accountnumber etc.</p>
<p>In providing us with this or any other information that may be required, you confirm that theinformation is accurate and authentic. You agree to update this information and keep it currentat all times.</p>

<p><span className="point-color">2.3</span> The LLP may use your information and documents to: <span className='point-color' >a)</span>provide Services; <span className='point-color' >b)</span> identify the User / fulfill the Know Your Customer requirements; c) process transactions; d) send periodic emails with updates, promotions, company news, and notices regarding changes to policies; e) customize, measure, and improve BitFlash’s Service and the content of the Platform; f) ensure compliance with applicable laws, best industry practicesand prevent potentially prohibited or illegal activities etc.; g)respond to and comply with requests received from various legal/statutory/regulatory authorities; h) marketing and promotion about the various services offered by BitFlash</p>
<p><span className="point-color"> 2.4</span> Notwithstanding anything contained in these Terms, the LLP shall be free to transfer/disclose any information shared by the User with the LLP, to a third party for provisioningof Services or as may be required under applicable laws. You authorize us to make theinquiries, whether directly or through third parties, that we consider appropriate, in our sole discretion, to verify your identity, complete your KYC requirements or protect you and/or us against fraud or other financialcrimes, and to take action we reasonably deem necessary based on the results of such inquiries.</p>
<p><span className='point-color' > 2.5</span> You hereby agree that You shall not use the Platform or our Service, in connection with any activity violating any law, statute, ordinance, or regulation of any jurisdiction, or for any other illegal, unlawful or unethical purpose. Further, You shall not exchange VCs using the Platform that are obtained through illegal / unlawful / fraudulent activities including without limitation money laundering or terrorist financing and You will also not use the Service to perform any illegal activity of any sort, in any jurisdiction, including but not limited to, money laundering, illegal gambling operations, terrorist financing, or malicious hacking.</p>
<p><span className='point-color' > 2.6</span> In the event the option is made available to You to transfer your VCs, You hereby agree that You shall not transfer/transmit the VC from Your Wallet to any third party’s cryptocurrency wallet. Further, You agree to not transfer/transmit the VC to any cryptocurrency wallet of any third party or a beneficiary or to a wallet outside India.</p>
<p><span className='point-color' > 2.7</span> Source of VCs exchanged by You is not known to BitFlash and You hereby agree to ensure that it always comes from legitimate sources within India. You are required to notify BitFlash immediately of any unauthorized use of the Platform or Service or Your BitFlash Account that You may become aware of, by way of an email addressed to support@BitFlash.co. The User who violates these Terms will get notified to the concerned authorities or get restricted from accessing the Platform and/or any other platform / service provided by the LLP, at LLP’s discretion. Further, such Users violating these Terms shall also be held liable and responsible for losses incurred by LLP or any other User of the Platform.</p>
<p><span className='point-color' > 2.8</span> BitFlash only acts as an information intermediary and a technology aggregator of various Virtual Currency exchanges. In case of any technical or manual error including but not limited to downtime and /or unavailability of BitFlash, the LLP will take reasonable steps to restore the Platform. If such correction creates a liability on You, You will be required to incur that liability.</p>
<p><span className='point-color' >2.9</span> You hereby acknowledge and agree that You currently do not have more than one BitFlash Account, and shall only maintain one BitFlash Account at all times</p>
<p><span className='point-color' >2.10</span> We have the right to disable your access to Your BitFlash Account or any part of it or suspend provisioning of the Services or the Platform or any part thereof, at any time, if in our reasonable opinion you have failed to comply with any of the provisions of these Terms including without limitation applicable laws.</p>
<p><span className='point-color' >2.11</span> You are responsible for maintaining the confidentiality and security of Your BitFlash Account, password, activities that occur in or through Your account and for restricting access to Your computer or mobile, as the case may be, and at all times, to prevent unauthorized access to / misuse of Your BitFlash Account. You agree to accept responsibility for all activities that occur under Your BitFlash Account or due to Your failure to protect the credentials / password. You should take all necessary steps to ensure that the password is kept confidential and secure and should inform us immediately if You have any reason to believe that Your password has become known to anyone else, or if the password is being, or is likely to be, used in an unauthorized manner. Any instructions or transactions initiated from Your BitFlash Account shall deem to be duly authorized by You unless otherwise promptly notified by You to Us, and We shall not be liable for acting on any such instruction / transaction / sale / purchase / other request on the Platform.</p>



 <h2>3. User Wallet</h2>
 <p><span className='point-color' >3.1</span> Upon activation of Your BitFlash Account, We will provide You with a VC wallet service (“Wallet”). The Wallet will enable you to buy or sell VC along with a separate Wallet for receiving /restoring the Virtual Currency. We reserve the right to refuse to execute any order and/transaction initiated by You, if they are in contravention of the policy of the Platform or fail to comply with directions of appropriate enforcement authorities or appear suspicious or malicious or without any rationale or basis or otherwise deemed necessary by Us in our reasonable discretion.</p>
 <p><span className='point-color' >3.2</span> Terms of Wallet</p>
 <p><span className='point-color' >a.</span>	A User can purchase VC either in exchange of another VC, as available, or in exchange of fiat currency ie. INR (Indian Rupee) using BitFlash’s partner exchanges through the Platform. Any denominated sale proceeds will also be credited into this Wallet, less the applicable Fee, in INR. You are not entitled to any interest on the funds held in the Wallet.</p>
<p><span className='point-color' >b.</span>	In order to purchase Virtual Currency on the Platform, You will be required to transfer fiat currency from Your linked bank account to your Wallet. Your Wallet will reflect fiat currency transferred to it within 7 (seven) working days of such transfer being initiated, subject to any delays in the relevant banking channels, payment gateways and/or other legal impediments.</p>
<p><span className='point-color' >c.</span>	You may withdraw the funds held in your Wallet, by making a formal request to transfer such funds into your linked bank account, through the Platforms at any time (“Withdrawal Request”). The LLP will endeavour to settle each Withdrawal Request within 7 (seven) working days of such request being made, subject to any delays in the relevant banking channels, payment gateways, and/or other legal impediments.</p>
<p><span className='point-color' >d.</span>You are not permitted to transfer, store or receive any VC not supported by our Platforms. You acknowledge that the LLP shall not be liable for any losses suffered by You in connection with your attempt to transfer, store or receive digital assets in contravention of this Clause and /or the Terms.</p>
<p><span className='point-color' >e.</span>BitFlash will process Wallet transactions according to Your instructions from Your BitFlash Account. You accept and agree that we do not:</p>
<p>guarantee the identity of any user, receiver, or other party to a Wallet transaction. You are solely responsible for ensuring all transaction details are correct, and You should carefully verify all transaction information prior to submitting transaction instructions to BitFlash; or</p>
<p><span className='point-color' >f.</span> You agree that Your Wallet is created/maintained/held within India.</p>
<p><span className='point-color' >g.</span> You agree that You shall not use the VC in Your Wallet to buy/sell/transfer/trade any good, services or products other than for availing Services through the Platform.</p>
<p><span className='point-color' >h.</span> You shall use only the Wallet assigned to You under Your BitFlash Account to avail the Services being provided by the LLP and shall not use or try getting access to a Wallet or BitFlash Account belonging to any other third party at any point of time.</p>
<p><span className='point-color' >i.</span> The LLP may suspend the account, trading service, Your BitFlash Account, deposit, and withdrawals of VCs / monies / fiat currency or Your User Wallet or any other service extended by it due to unforeseen situations, change of law, force majeure maintenance or any other reason as it deems fit in its sole discretion and You acknowledge that Your access to the funds/ crypto-currency/ Your BitFlash Account/ Your Wallet/ Services in case of such an instance may be limited or restricted or suspended, partially or fully. You accordingly understand and acknowledge that the LLP shall have no liabilities or obligations arising from such events.</p>
<p><span className='point-color' >j.</span>	Any withdrawal requests from the Wallet will also be subject to the KYC policy of the LLP and the User shall only be able to make a successful request from withdrawal from Wallet upon submission of all the necessary documents as required by LLP to establish and verify your identity.</p>
<p><span className='point-color' >k.</span>	You shall inform Us in writing within 15 days, if any irregularities or discrepancies exist in the Transactions/ particulars of the Wallet on any statement / records that is made available to you. If We do not receive any information to the contrary within 15 days, We shall assume that the statement and the transactions are correct. All records maintained by Us, in electronic or documentary form of the instructions of the User and such other details (including but not limited to payments made or received) pursuant to the Terms and conditions herein, shall as against the User, be deemed to be conclusive evidence of such instructions and such other details.</p>
<p><span className='point-color' >l.</span>	You must ensure the availability of sufficient funds before executing any transaction from the Wallet.</p>
<p><span className='point-color' >m.</span>	In case of any dispute relating to the time of reporting and/ or transaction/s made on the Wallet or any other matter in relation to the said Wallet, We reserve the right to ascertain the time and/ or the authenticity of the disputed transaction.</p>
<p><span className='point-color' >n.</span>	When you make a deposit, you are liable to BitFlash for the full amount of the deposit plus any fees, if the deposit is later invalidated for any reason. This means that, in addition to any other liability, you will be responsible for the amount of the deposit, plus applicable fees if you lose a claim or a chargeback, or if there is a reversal of the deposit. If You or the owner of the funding source of a deposit later disputes the deposit or files a claim for a chargeback, the debit or credit card issuer or the originating bank, or BitFlash, will determine whether the dispute is valid and to whom payment is due. You agree to allow BitFlash to recover any amounts due to Us by debiting your Wallet balance. If there are insufficient funds in your account to cover your liability, you agree to reimburse BitFlash through other means. If BitFlash is unable to recover the funds from your primary funding source, We may attempt to contact you and/or recover the funds from your alternate funding sources, or may take other legal actions to collect the amount due, to the extent allowed by applicable law. In addition, We may suspend or terminate your Wallet.</p>
<p><span className='point-color' >o.</span>You can choose to withdraw the funds available from Your Wallet to the source from which the payment loading originating or to a verified bank account.</p>
<p><span className='point-color' >p.</span>In an event where We are unable to transfer the funds back to source or to a bank account, We will transfer the funds to your bank account by way of NEFT.</p>
<p><span className='point-color' >q.</span>BitFlash shall, upon adequate verification, block/suspend/close the Wallet and terminate all facilities in relation thereto during working hours on a working day following the receipt of such intimation and shall not be liable for any inconvenience caused to the wallet holder in this regard.</p>
<p><span className='point-color' >r.</span>You can choose to close down Your account and Wallet and request for funds to be transferred back to a bank account by writing to support@BitFlash.co and furnishing proof of being the holder of the said account.</p>
<p><span className='point-color' >s.</span>	We may also restrict, terminate or suspend the use of Wallet at any time without prior notice if We or the bank reasonably believes it necessary for business or security reasons.</p>
<p><span className='point-color' >t.</span>	You accept full responsibility for wrongful use of the Wallet and which is in contravention of these terms and conditions or any applicable law. You shall indemnify Us to make good any loss, damage, interest or any other financial charges that We may incur and or suffer whether directly or indirectly due to any act or omissions resulting in any violations of these terms and conditions or any applicable law.</p>
<p><span className='point-color' >u.</span>	We reserve the absolute discretion and liberty to decline or honour the authorization request on the Wallet without assigning any reason thereto.</p>
<p><span className='point-color' >v.</span>	You understand that these terms and conditions shall be applicable to all transactions made through Platform including wallet transactions.</p>
<p><span className='point-color' >w.</span>	We reserve the right to block any person from making bank transfers if there are reasonable grounds to believe that the same is not in accordance with applicable law and/or it is suspicious that the User is misusing or fraudulently transacting. We shall report such suspicious activities to the concerned statutory/police departments.</p>
<p><span className='point-color' >x.</span>	In case of transactions suspected to be of fraudulent nature or upon receipt of any complaints from concerned banks / payment gateways / regulatory authorities, We may block the User's Wallet and any amounts contained therein till such time as the enquiry is completed and take appropriate steps thereafter.</p>
<p><span className='point-color' >y.</span>	We will monitor each deposit made into your Wallet to monitor high-risk & fraudulent transactions. If Your deposit is classified as a high-risk transaction or is suspected of fraud, We will place a hold on the deposit and may ask You for more information on You and Your funding source. We will conduct a review and will accordingly either clear or cancel the deposit. If the deposit is cleared, We will notify you and update your Wallet. Otherwise, We will cancel the deposit and the funds will be forfeited. The said funds will be refundable only to the source account upon valid demand raised by the holder of the source account. We will notify you by email and/or in the account history tab of your Wallet if the deposit is canceled. We reserve the right to delay withdrawals while screening for risk, or request you provide additional information to verify Your identity and may limit the amount you can withdraw until the information is verified.</p>
<p><span className='point-color' >z.</span>	Any withdrawal found to be suspicious will be held back and reversed into Wallet. The Wallet will also be suspended for operations and no transactions will be possible pending an investigation. A notification will be given to you if you are the subject of an investigation. If you are able to provide a justification for the withdrawal to the satisfaction of BitFlash, Your account will be removed from suspension and you would be free to transact using your Wallet. In the case of no information being provided by you for a suspended Wallet – the Wallet will continue to be suspended till its validity and the amount will be forfeited as required by any applicable laws.</p>


 <h2>4. Activities Prohibited on the Platform</h2>
 <p><span className='point-color' >4.1</span> BitFlash has zero tolerance towards use of its Services for any illegal purpose. Any such abuse by any User shall result in forthwith restriction of access and reporting of such activities to concerned regulatory and statutory authorities as required. BitFlash shall report all suspicious, malicious, unethical and illegal activities to the concerned authorities to ensure initiation of investigation and prosecution against You, if and as required.</p>
<p><span className='point-color' >4.2</span> In connection with your use of Services and/or Platform, You hereby agree that you will not:</p>
<p><span className='point-color' >a.</span>	violate (or assist any other party in violating) any applicable law, statute, ordinance, or regulation;</p>
<p><span className='point-color' >b.</span>	intentionally try to defraud (or assist in the defrauding of) the LLP or any other User;</p>
<p><span className='point-color' >c.</span>	make any representations on behalf of BitFlash;</p>
<p><span className='point-color' >d.</span>	provide false, inaccurate, or misleading information;</p>
<p><span className='point-color' >e.</span>	trade taking advantage of any technical glitch, malfunction, failure, delay, default, or security breach;</p>
<p><span className='point-color' >f.</span>	take any action that interferes with, intercepts, or expropriates any system, data, or information;</p>
<p><span className='point-color' >g.</span>	partake in any transaction involving the proceeds of illegal activity;</p>
<p><span className='point-color' >h.</span>	attempt to gain unauthorized access to other user accounts, the Services, or any related networks or systems;</p>
<p><span className='point-color' >i.</span>	use the Services on behalf of any third party or otherwise act as an intermediary between BitFlash and any third parties or acting for benefit of any third party;</p>
<p><span className='point-color' >j.</span>	use the Services/Platform for any benami transaction;</p>
<p><span className='point-color' >k.</span>	use the Services to engage in conduct that is detrimental to LLP or to any other user or any other third party or the public at large;</p>
<p><span className='point-color' >l.</span>	collect any user information from other users, including, without limitation, email addresses;</p>
<p><span className='point-color' >m.</span>	participate in any unfair trade practice or market manipulation, including but not limited to all such acts like pump and dump schemes, trading on any inside or non-public information acquired through sources or acts not permitted by law, wash trading, trading for the purposes of market manipulation, spoofing or layering etc.</p>
<p><span className='point-color' >n.</span>	use the Services being provided by the LLP to violate public morale, any third party/ public interest or for any act being not permitted by the law of the land;</p>
<p><span className='point-color' >o.</span>	use multiple devices to access or log into Your BitFlash Account at a given point of time, i.e. You shall not access Your BitFlash Account through multiple devices simultaneously nor shall You ever use or try to gain access to any other third party BitFlash Account not belonging to You;</p>
<p><span className='point-color' >p.</span>	duplicate, distribute, create derivative works of display or commercially exploit the Platform or any of its content, features or facilities, directly or indirectly, without Our prior written permission nor would You have access to the Platform in source-code form;</p>
<p><span className='point-color' >q.</span>	without the prior written consent of BitFlash, modify, replicate, duplicate, copy, download, store, further transmit, disseminate, transfer, disassemble, broadcast, publish, remove or alter any copyright statement or lable, or license, sub-license, sell, mirror, design, rent, lease, private label, grant security interest in the properties or any part of the properties, or create their derivative works or otherwise take advantage of any part of the properties;</p>
<p><span className='point-color' >r.</span>	defame, harass, or violate the privacy or intellectual property rights of the LLP or any other user; or</p>
<p><span className='point-color' >s.</span>	upload, display or transmit any messages, photos, videos or other media that contain illegal goods, pornographic, violent, obscene or copyrighted images or materials for use as an avatar, in connection with a payment or payment request, or otherwise.</p>
<p><span className='point-color' >t.</span>	In addition, you agree not to: a) use circumvention or obfuscating technologies to mask their IP addresses or to hide transaction details; b) create or circulate any technologies which violate, or which would facilitate other users to violate the terms hereof including for masking IP addresses or to obfuscate transaction details; c) misrepresent, misinform or misguide BitFlash in any manner; d) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the internet.</p>
<p><span className='point-color' >4.3</span> BitFlash reserve the right to investigate and/or take appropriate action against You in Our sole discretion if You engage in prohibited activities or violate any other provision of these Terms or otherwise create liability for Us or any other person or there is any reasonable suspicion or allegation or complaint from any legal / public / regulatory / statutory authority. Such action may include, in Our sole and absolute discretion, terminating Your BitFlash Account, reporting you to law enforcement authorities without providing any notice to You about any such report and confiscating any balance remaining in Your BitFlash Account which has been terminated.</p>
<p><span className='point-color' >4.4</span> Users are cautioned against undertaking any suspicious activity on or through the Platform or Services. In the event of any suspicious or large transactions being undertaken by You, BitFlash shall have the right but not the obligation to verify such activity by sharing Your IP address and other KYC details with the relevant authority, and if required, suspend the transactions or freeze your access.</p>

<h2>5. Fee:</h2>
<p><span className='point-color' >5.1</span> Trading on the Platform is subject to payment of a fee on each transaction executed / facilitatedthrough the Platform.</p>
<p><span className='point-color' >5.2</span> The transfer of digital assets in the BitFlash wallet is free of charge. Transfer of fiat currency through credit card, debit card, or net banking will be subject to a transaction fee. You may be charged a fee on the withdrawal of the digital asset from Your Wallet. Transfers and withdrawals of digital assets or fiat currency will be subject to such limit as may be notified on the Platform from time to time.</p>



 <h2>6. Taxes:</h2>
 <p>It is Your responsibility to determine, collect, report, and submit any/all taxes applicable to thepayments and/or your digital assets you make or receive in connection with the use of the Platform and the Service to the appropriate tax authority in India or under any other applicable laws. BitFlash is not responsible fordetermining whether taxes apply to your transactionor the VCs owned by You or Your Wallet, or for collecting, reporting or remitting any taxes arising from any transaction undertaken via the Platform or Services.</p>



<h2>7. Privacy Policy: </h2>
<p><span className='point-color' >7.1</span> You understand that BitFlash collects information with respect to your VC wallet addresses, transactions and your IP address. BitFlash does not in any way obscure the information that it does request or obtain. Due to the inherent transparency of blockchains of VCs, transactions to and from the Platform and Services are public, and may be disclosed by Us, to any third party, including but not limited to government regulators.</p>
<p><span className='point-color' >7.2</span> Know Your Customer Requirements: We are committed to protecting our Users from fraud, scam and other such financial crimes, and to comply with all applicable laws and industry practices. In order to prevent illegal activities, it is necessary to take measures to verify the identity of the customer and authenticity of the transactions. You agree to share personal information including, but not limited to, Your name, e-mail address, contact information, Government issued ID etc. as may be requested from time to time. The Know Your Customer (KYC) details may be requested by BitFlash independently as per its own discretion or upon receipt of a request from a VC exchange or any law enforcement authority under any law. The KYC information will be used, specifically for identification of a user, detection of all illicit and illegal acts including but not limited to money laundering, terrorist financing, fraud, suspicious, malicious transactions and various other related financial crimes and to comply with any requests from any lawful authority.You also authorise us to make inquiries, either directly or through third parties, that are deemed necessary for this purpose. BitFlash may also use third party services to collect and verify User’s KYC information/ documents.</p>
<p><span className='point-color' >7.3</span> We may also place cookies on Your device while You access the Platform and/or the Services. Cookies collect User information including Platform usage, visits to the Platform and other User generated information. Cookies allow Users to navigate from page to page without having to re-login each time, count visits, and see which areas and features of the Platform are popular.</p>
<p><span className='point-color' >7.4</span> Any sensitive information in these cookies are encoded so that only BitFlash can interpretthe information stored on them. The cookies are placed for the following purposes:
•	Recognize You as a BitFlash User,
•	Collect information about Your computer / mobile device to mitigate risk and help prevent fraud,
•	Customize Your experience, content, and advertising, and
•	Measure promotional effectiveness.
Further, the use of cookies and other technologies may allow BitFlash and third parties tocollect information about User browsing activities over time and across different websitesfollowing use of Service.</p>
<p><span className='point-color' >7.5</span> BitFlash may also uses third party analytical and other tools / services to collect data about the usage of the Platform or Services. The information collected identifies the types and timing of actions taken,including installation, registration, uploading, and certain types of navigation. All thisinformation is used internally for the purpose of understanding how the Platform is being usedand to improve the same.</p>
<p><span className='point-color' >7.6</span> You hereby agree and provide your consent to receive all communications at the telephone number and e-mail address provided, even if this telephone number is registered under DND/NCPR list under TRAI regulations or the re-enactment /modification or amendment thereof. And for that purpose, You further authorize LLP to share/disclose the information to any third party service provider or any affiliates, group companies, their authorised agents or third-party service providers.</p>
<p><span className='point-color' >7.7</span> This Clause 7 is in addition to the Privacy Policy available at https://BitFlash.co/privacy-policy Please read the Privacy Policy for further details.</p>



 <h2>8. Risks:</h2>
 <p>The use of the Platform and the Service may entail the following risks:</p>
 <p><span className='point-color' >8.1</span> Virtual Currency transactions are irreversible after they hit the network and once a transactionis initiated by you, it can neither be cancelled, modified nor reversed by Us upon Your request.</p>
 <p><span className='point-color' >8.2</span> Sale and/ or purchase transactions initiated by You on the Platform are final, irreversible, non-refundable and non-cancellable. Once a sale/ purchase and/ or any other fiat or VC transaction is initiated by You on the Platform, the said transaction is absolute and unconditional. You cannot seek or claim or demand refund or reversal for any reason whatsoever nor can it be canceled, modified or reversed by Us/ anyone else upon Your/ third-party request.</p>
 <p><span className='point-color' >8.3</span> The values of VCs are highly volatile and tend to fluctuate, due to which there may be anincrease or decrease in the value of the VC You receive after conversion. VCs are subject tolarge swings in value and may even become worthless. There is always an inherent risk oflosses associated with buying, selling, or trading in VCs. It is also possible that the valuationand price of VC changes after the transaction has been initiated by You or during the transaction,and You are hereby advised/ cautioned of the same. Value of a VC is subject to market change, under nocircumstance shall BitFlash be liable for any such changes or fluctuations whether before,during or after the transaction.</p>
 <p><span className='point-color' >8.4</span> VCs are as yet autonomous and largely unregulated. It is not backed by any government or commodities nor is it is a legal tender in India nor is it a regulated investment /security in India, and hence may besusceptible to risks not generally associated with other forms of legal tenders/ investments.</p>
 <p><span className='point-color' >8.5</span> As VC is digital asset managed by a peer-to-peer system of networks, there is also the risk ofloss of confidence in VC trading. The VCs do not guarantee any assured returns as the valuation of VCs is based on a supply and demand economy model, and is therefore, subject to constant changes.</p>
 <p><span className='point-color' >8.6</span> There may be additional risks that we have not foreseen or identified in these Terms of Use.</p>
 <p><span className='point-color' >8.7</span> You should carefully assess whether your financial situation and tolerance for risk is suitablefor buying, selling, or trading VCs.</p>
 

<h2>9. Limited Right of Use: </h2>
<p>Unless otherwise specified, all content,logo, material, design, graphic symbols etc (“Materials”) on this Platform are the property of the LLP and are protected by copyright, trademark, and other applicable laws. You may view such Materials on any single computer solely for Your use, provided You keep intact all copyright and other proprietary notices. The trademarks, service marks, and logos of BitFlash and others used in this Platform (" Trademarks ") are the property of the LLP and their respective licensors. The software, text, images, graphics, data, prices, trades, charts, graphs, video, and audio used on this Platform belong to the LLP. The Trademarks and Materials should not be copied, reproduced, modified, republished, uploaded, posted, transmitted, scraped, collected or distributed in any form or by any means, whether manual or automated. The use of any such Materials on any other website or networked computer environment for any other purpose or other commercial / non-commercial reasons is strictly prohibited; any such unauthorized use may violate copyright, trademark, and other applicable laws and could result in criminal or civil legal actions and penalties.</p>



 <h2>10. Limitation of Liability:</h2>
 
 <p><span className='point-color' >10.1</span> Users of this Platform are responsible for their actions in connection with the use of the Platform and/or Service/ BitFlash Account and Wallet.</p>
 <p><span className='point-color' >10.2</span> BitFlash is not responsible for the outcome, whether positive or negative, of any action performed by any of its Users within or related to the VCs / Platform / Service.</p>
 <p><span className='point-color' >10.3</span> The Parties agree that in no event shall BitFlash or its affiliates, officers, directors, agents, employees, and suppliers be liable for lost profits or any special, incidental or consequential damages arising out of or in connection with the use of our Platform, Service, or these Terms of Use.</p>
 <p><span className='point-color' >10.4</span> User shall not invest in VCs under any assumption of high earnings or profits. VCs being digital assets issued by private entrepreneurs are subject to market risks and volatile pricing, which may even render them worthless. Users are therefore again cautioned of the inherent risks involved in procuring VCs.</p>
 <p><span className='point-color' >10.5</span> Use of BitFlash may carry risks as also detailed in the Risk section above and is to be used as an experimental software only. In no event shall BitFlash be liable or responsible for any damages, claims, applications, losses, injuries, delays, accidents, costs, business interruption costs, or other expenses (including, without limitation, attorneys’ fees or the costs of any claim or suit), nor for any incidental, direct, indirect, general, special, punitive, exemplary, or consequential damages, loss of goodwill or business profits, loss of VCs or digital assets, work stoppage, data loss, computer failure or malfunction, or any other commercial or other losses directly or indirectly arising out of or related to these Terms, the Privacy Policy, any service of BitFlash, the use of BitFlash, exchange of Your digital assets or VCs by any other party authroised / not authorized by You (collectively, all of the foregoing items shall be referred to herein as "Losses"). BitFlash is hereby released by You from liability for any and all Losses. The foregoing limitation of liability shall apply whether the alleged liability or Losses are based on contract, negligence, tort, strict liability, or any other basis, even if BitFlash has been advised of or should have known of the possibility of such losses and damages, and without regard to the success or effectiveness of other remedies. Notwithstanding anything else in these Terms of Use or any other document, in no event shall the combined aggregate liability of BitFlash for any Loss exceeding INR 5000/- (Rupees Five Thousand Only). In the event that any transfers of VCs are erroneously credited, the User is bound to report the same and to arrange to refund or transfer it to relevant VC exchange or to the rightful owner, as confirmed by the relevant VC exchange, at its own cost and expense. The failure to do so would amount to a material breach and entitle BitFlash to additional remedies available through court processes.</p>
 <p><span className='point-color' >10.6</span> In the event a User resides in any such jurisdiction outside of India,Users shall not use the Platform and/or the Services to conduct any transaction in VCs. If suchtransgression is brought to the notice of BitFlash, the LLP shall forthwith restrict youraccess and use of the Platform / Service. The Parties agree that the Users shall be solely responsible for ensuringcompliance with the above duty and responsibility to follow the laws of the country of residence and India.</p>
 <p><span className='point-color' >10.7</span> These Terms are subject to confirmation by the Government of India, of the legality of dealing in VCs and in the event that the Government of India were to hold such dealing to be invalid or illegal in India, this agreement shall stand automatically terminated without further notice or recourse available to User. BitFlash has given full disclosure of the current Government and regulatory status with respect to VCs in India and the risk involved in dealing with or trading in the same. By accessing the Platform and/or the Services, You are deemed to have understood, agreed to and accepted the risk and costs with respect to the same including but not limited to total / complete loss / seizure of Your Wallet and/or VCs.</p>
 <p><span className='point-color' >10.8</span> Your ability to use the Services may be detrimentally impacted by regulatory action or changesin regulations applicable to VCs. If We are unable to perform the Service outlined inthe Terms due to factors beyond our control including but not limited to an event of forcemajeure, change of law or change in sanctions policy, We will not have any liability to you withrespect to the Platform / Service provided under these Terms of Use and for a time periodcoincident with the event.</p>



 <h2>11. Financial Regulation and Advice:</h2>
 <p><span className='point-color' >11.1</span> We do not provide any investment advice or financial advice in connection with the Service contemplated by these Terms of Use. While We may provide information on the value, range, volatility of VCs, and events that may affect/have affected the value of VCs directly on the Platform or through other social media channels, this is not considered investment advice and should not be construed or relied on as such. BitFlash will not be liable for any loss suffered by You in connection with any transaction involving BitFlash / the Service or the Platform.</p>
 <p><span className='point-color' >11.2</span> Our business model, and our Service, consists of facilitating the buying and selling of VCs in an unregulated yet responsible, international open payment system. The Service we provide is currently unregulated within India.</p>




<h2>12. Assignment: </h2>
<p>You acknowledge and agree that the LLP can freely assign these Terms of Use or any of its rights under these Terms of Use to any person without Your consent. You shall however, not be entitled to assign these Terms of Use, in whole or in part, to another person without the prior written approval of the LLP.</p>



 <h2>13. Additional Terms:</h2>
 <p><span className='point-color' >13.1</span> The Platform may provide links or other forms of reference to other websites (" External Platforms ") or resources over which We have no control. You acknowledge that BitFlash is providing any such links or references of external platforms or resources to You, including APIs to various Virtual Currency exchanges, only as a convenience to You and that BitFlash makes no representations whatsoever about any external platforms which You may access through or via this Platform, including such external platforms being free of such items as viruses, worms, trojan horses, and other items of a destructive nature. BitFlash is not responsible for the availability of, and content provided on any external platforms. You are requested to review the terms of use and policies posted by such external platforms regarding privacy and other topics before use. BitFlash is not responsible for third party content accessible through the Platform, including opinions, advice, statements, prices, activities, and advertisements, and You shall bear all risks associated with the use of such content or trading VCs on such external platform.</p>
 <p><span className='point-color' >13.2</span> BitFlash has no control over the generation, distribution, retention, or termination of VCs. BitFlash does not control market volatility of VCs. It merely acts as a technology intermediary for the services offered, which are more fully set out herein above.</p>
 <p><span className='point-color' >13.3</span> BitFlash does not provide any warranty of any kind, either express or implied. Services and the Platform and any information or content contained therein is provided on an “as-is” and “as available” basis. User avails of the Services and / or dealing in VCs does so at their own risk and with full disclosure of possible wiping out of the entire holding or valuation, in the event of the occurrence of any of the risk factors including but not limited to changes in regulatory or legal position in India or restrictions that may be placed on BitFlash, it is hereby expressly declared that BitFlash offers no warranty of any kind regarding the Platform or the Services or Your BitFlash Account or Wallet.</p>
 <p><span className='point-color' >13.4</span> Caution by RBI : The Reserve Bank of India (" RBI ") has issued multiple circulars cautioning users regarding the risks involved with respect to VCs. Users in India shall therefore avail of the Services and access the Platform subject to the above caution issued by the RBI and solely at their own risk. You further understand that trading in cryptocurrencies is not regulated in India and involves a considerable level of risk. Cryptocurrencies are subject to frequent changes and the value of your cryptocurrency will constantly fluctuate, You may even also suffer a total loss. You understand that that LLP has no liability, and that You are solely responsible for your decisions while dealing / trading in cryptocurrency. You further understand that past performance of cryptocurrencies is not indicative of future prices / value. Any sale / purchase shall be at Your own risk and subject to your independent assessment, and the LLP has no liability towards the same.</p>
 <p><span className='point-color' >13.5</span> Sanctions: By accessing and using the Services and / or the Platform and / or any part thereof, you represent and warrant that you are not on any trade or economic sanctions lists, such as the UN Security Council Sanctions list, designated as a “Specially Designated National” by OFAC (Office of Foreign Assets Control of the U.S. Treasury Department) or placed on the U.S. Commerce Department’s “Denied Persons List” , Cuba, Iran, North Korea, Crimea, Sudan, Syria. You are required to ensure that your jurisdiction permits lawful trading in VCs. In the event that it doesn’t, please discontinue the use of the Service or the Platform immediately.</p>
 <p><span className='point-color' >13.6</span> Compliance with Applicable Laws: BitFlash does not encourage the violation of any laws and cannot be held responsible for violation of such laws in India or any jurisdiction of the world.</p>
 <p><span className='point-color' >13.7</span> You acknowledge and agree that BitFlash will have no obligation to provide you with any support or maintenance in connection with the Services / Platform.</p>
 <p><span className='point-color' >13.8</span> You acknowledge that all the intellectual property rights, including copyrights, patents,trademarks, and trade secrets, in the Services and its content are owned by BitFlash or itssuppliers. Neither these Terms(nor your access to the Services) transfer to You or any third party any rights, title or interest in or to such intellectual property rights, except for the limitedaccess rights expressly set forth in the Terms. BitFlash and its suppliers reserve all rights not granted in these Terms. There are no implied licenses granted herein whatsoever.</p>
 <p><span className='point-color' >13.9</span> BitFlash does not guarantee that your use of the Services or any part thereof will always be available/ uninterrupted / error-free. Access to BitFlash / Services is permitted on a temporary basis and “as is” – “as available” basis. We may suspend, withdraw, discontinue or change all or any part of Service including Your BitFlash Account and/or Wallet, without notice. BitFlash will not be liable to you including without limitation for any losses due to the unavailability of any Service / Platofrm or any part thereof at any time or for any period.</p>


 <h2>14. Termination and Suspension:</h2>
 <p><span className='point-color' >14.1</span> You may terminate this agreement with Us, at any time, following settlement of any pending transactions.</p>
<p><span className='point-color' >14.2</span> You agree that LLP may, by giving notice, in its sole discretion, restrict your access to the Platform; including without limitation, suspending or terminating the Service, prohibiting access to the Platform and its content, services and tools, delaying or removing hosted content, and taking technical and legal actions to keep You off the Platform if We, in our sole discretion, reasonably perceive that You are creating any problems, including without limitation, possible legal liabilities, infringement of the intellectual property rights, or acting inconsistently with the letter or spirit of these Terms of Use.</p>
<p><span className='point-color' >14.3</span> We may, in appropriate circumstances and at our sole discretion, initiate the above actions for any reason, including without limitation:</p>
<p><span className='point-color' >a.</span>	Attempts to gain unauthorized access to the Platform or providing assistance to others’ attempting to do so;</p>
<p><span className='point-color' >b.</span>	Usage of the Service to perform illegal activities such as money laundering, illegal gambling operations, financing terrorism, or other criminal activities;</p>
<p><span className='point-color' >c.</span>	Violations of these Terms of Use / Privacy Policy;</p>
<p><span className='point-color' >d.</span>	Failure to pay or fraudulent payment for transactions;</p>
<p><span className='point-color' >e.</span>	Unexpected operational difficulties; or</p>
<p><span className='point-color' >f.</span>	Upon the request of law enforcement or other government agencies.</p>
<p><span className='point-color' >14.4</span> BitFlash may terminate Your BitFlash Account or Your Wallet or suspend your access to the Services / Platform or any part thereof at any time and with immediate effect for any reason or no reason, in our sole discretion. We may decline to process any deposit or withdrawal (of VCs / monies / Your BitFlash Account / Your User Waller) or any other service offered by us or any part thereof without any notice and may limit or suspend your use of one or more Services at any time, in our sole discretion. BitFlash may delay deposits or withdrawals if we believe the transaction is suspicious, may involve fraud or misconduct, violates applicable laws, or violates the terms of this Agreement or is otherwise required, in our sole and absolute discretion. You understand that BitFlash shall have no liability or responsibility for such termination / suspension or any losses arising therefrom.</p>
<p><span className='point-color' >14.5</span> If you have a balance remaining in Your BitFlash Account / Wallet which has been suspended, we may freeze such balance for so long as the Account / Service is suspended. If the Account is terminated due to fraud, violation of law, or violation of this Agreement or other reasonable cause as determined by BitFlash, we may, in our discretion, confiscate the balance remaining in Your BitFlash Account / Wallet and deliver it to any applicable government, law enforcement, or other authorities where circumstances warrant.</p>
<p><span className='point-color' >14.5</span> Consequences of Termination:Upon termination of this Agreement or earlier determination, the rendering of the Services shall stand immediately terminated by the LLP and the User shall not be entitled to access or avail the Platform. the LLP shall continue to retain your information and data as per its Privacy Policy to ensure compliance with its legal obligations, and for audit and recording purposes.</p>

 <h2>15. Indemnity:</h2>
 <p>To the full extent permitted by applicable law, you hereby indemnify, defend and hold- harmless BitFlash, and its affiliates, officers, directors, agents, employees, and suppliers against any Losses, action, liability, cost, claim, loss, damage, proceeding or expense suffered or incurred from your use of the Platform and/or Service / Your BitFlash Account / Your Wallet and/or from your violation of these Terms.</p>



 <h2>16. Modification of Terms:</h2>
 <p>BitFlash reserves the right to change, add or remove or modify the Platform, the Service, theTerms, or any content or part thereof, at any time, with or without notice, in its sole discretion. BitFlash shall have no liability or responsibility whatsoever due to such changes, additions, removals and modifications, as the case may be</p>



<h2>17. Contact: </h2>
<p>If You have any questions relating to these Terms of Use, Your rights and obligations arising from these Terms of Use and/or Your use of the Platform and the Service, or any other matter, please contact us at  support@BitFlash.co  .</p>

<h2>18. Jurisdiction: </h2>
<p>These Terms of Use shall be governed and construed in accordance with the laws of India. The Parties agree to irrevocably submit to the exclusive jurisdiction of the courts in Bangalore for the resolution of any disputes arising from these Terms of Use.  .
Disclaimers</p>

<p>Crypto is an unregulated digital asset, not a legal tender and subject to market risks. All investments are subjected to price fluctuation risk. BitFlash does not guarantee any assured returns or profit.</p>

<p>Any content/ information/ data/ video/ articles ("Content") that You might see on the Platform and/ or under Our brand name is for informative purposes only. It is not intended as a substitute for investment/ financial advice. If You decide to act upon this information, You shall do it at your own risk. While such Content has been verified, it depends on third-party sources too, and BitFlash does not guarantee that there are no mistakes or errors nor does BitFlash represents the views presented in such Content to be it's own</p>


            </div>
        </div>
        <Footer/>

        </>
    )
}